border_radius=8
blur=1
borderpx=1
focuscolor=0xb37becff
animations=1
layer_animations=1
animation_type_open=slide
animation_type_close=slide
layer_animation_type_open=slide
layer_animation_type_close=slide
animation_duration_move=200
animation_duration_open=200
animation_duration_close=200
animation_duration_tag=200
animation_duration_focus=500
animation_fade_in = 0
animation_fade_out = 0
layerrule=layer_name:selection,noanim:1
tag_animation_direction = 0  # vertical
