bind=Super,H,focusstack,prev
bind=Super,L,focusstack,next
bind=Super+Shift,H,exchange_stack_client,prev
bind=Super+Shift,L,exchange_stack_client,next
bind=Super+Shift,J,tagtoright
bind=Super+Shift,K,tagtoleft
bind=Super,J,viewtoright,d
bind=Super,K,viewtoleft,u
bind=Super,B,togglefloating
bind=Super+Ctrl+Shift,bracketleft,spawn,hyprlock

bind=Alt,F,togglefullscreen
scroller_proportion_preset=0.5,1
bind=Super,F,switch_proportion_preset,0.5,1
scroller_default_proportion=0.5
edge_scroller_pointer_focus=0

axisbind=Super,Up,focusstack,prev
axisbind=Super,Down,focusstack,next
mousebind=SUPER,btn_left,moveresize,curmove
mousebind=SUPER,btn_right,moveresize,curresize

bind=Super,Return,spawn,kitty
bind=Super+Shift,Q,killclient
bind=Super,e,spawn,librewolf
bind=Super+Shift,R,reload_config
bind=Alt+Shift,S,spawn,~/usrbin/wayscreenshot
bind=Super+Shift,E,spawn,wleave
focus_on_activate=0

bind=Super,W,setlayout,tile
bind=Super,Q,setlayout,scroller

enable_hotarea=0
ov_tab_mode=1
bind=Super,Tab,toggleoverview



sloppyfocus=1

#monitorrule=name,mfact,nmaster,layout,transform,scale,x,y,width,height,refreshrate
monitorrule=HDMI-A-2,0.55,1,scroller,0,1,1920,0,1920,1080,120
monitorrule=HDMI-A-1,0.55,1,tile    ,0,1,0   ,0,1920,1080,60
