bind=Super,1,view,1
bind=Super,2,view,2
bind=Super,3,view,3
bind=Super,4,view,4
bind=Super,5,view,5
bind=Super,6,view,6

bind=Super+Shift,1,tag,1
bind=Super+Shift,2,tag,2
bind=Super+Shift,3,tag,3
bind=Super+Shift,4,tag,4
bind=Super+Shift,5,tag,5
bind=Super+Shift,6,tag,6
bind=Super+Shift,7,tag,7
